# Generated by Django 2.2.16 on 2020-09-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_detaile',
            fields=[
                ('eno', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=100)),
                ('esalary', models.FloatField()),
                ('eaddress', models.TextField(max_length=200)),
            ],
        ),
    ]
