# Generated by Django 2.2.16 on 2020-09-06 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('source_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cus_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cus_name', models.CharField(max_length=100)),
                ('geo_lat', models.CharField(blank=True, max_length=100, null=True)),
                ('geo_long', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmark_app.Bookmark')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmark_app.Customer')),
            ],
        ),
    ]
