# Generated by Django 2.2.16 on 2020-09-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmark_app', '0002_auto_20200906_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='Booking_date',
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='book_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
