# Generated by Django 3.1.1 on 2020-09-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roles',
            name='role_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
