# Generated by Django 2.2.16 on 2020-09-08 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dept_id',
            new_name='dept_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dept_Name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role_id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='role_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Roles'),
        ),
    ]
