# Generated by Django 2.2.16 on 2020-09-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_auto_20200908_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
